CREATE TABLE
  M_CATEGORY (
    CATEGORY_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    CATEGORY_NAME CHARACTER VARYING NOT NULL,
    ENTRY_DATETIME TIMESTAMP NOT NULL DEFAULT NOW (),
    UPDATE_DATETIME TIMESTAMP NOT NULL DEFAULT NOW (),
    DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (CATEGORY_ID)
  );