CREATE TABLE
  T_STREAM (
    STREAM_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    TITLE CHARACTER VARYING NOT NULL,
    OVERVIEW CHARACTER VARYING NOT NULL,
    CATEGORY_ID BIGINT NOT NULL REFERENCES M_CATEGORY (CATEGORY_ID),
    USER_ID CHARACTER(36) NOT NULL REFERENCES T_USER (USER_ID),
    ENTRY_DATETIME TIMESTAMP NOT NULL DEFAULT NOW (),
    UPDATE_DATETIME TIMESTAMP NOT NULL DEFAULT NOW (),
    DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (STREAM_ID)
  );