CREATE TABLE T_USER (
  USER_ID CHARACTER(36) NOT NULL DEFAULT gen_random_uuid ()::text,
  PASSWORD CHARACTER VARYING NOT NULL,
  USER_NAME CHARACTER VARYING NOT NULL,
  ENTRY_DATETIME TIMESTAMP  NOT NULL DEFAULT NOW(),
  UPDATE_DATETIME TIMESTAMP  NOT NULL DEFAULT NOW(),
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (USER_ID)
);